version: '2'
services:
  app:
    image: eacraft13/blackjack-app
    command: npm start
    environment:
      NODE_ENV: development
    volumes:
      - ./app/:/home/blackjack/app/
      - /home/blackjack/app/node_modules/
    ports:
      - '80:8080'
    networks:
      - blackjack
networks:
  blackjack:
